window.Constants = {
		//URL_BASE:"http://192.168.0.102:8080/consorciomovil/api",
		URL_BASE:"http://200.58.118.223:8080/consorciomovil/api",
		
		ROLE_USER:"user",
		ROLE_ADMINISTRATOR:"administrator",

		MESSAGE_ORIGIN_USER:"USUARIO",
		MESSAGE_ORIGIN_ADMINISTRATOR:"ADMINISTRADOR",

		MESSAGE_ANSWERED_YES:"SI",
		MESSAGE_ANSWERED_NO:"NO",
		
		MESSAGE_TYPE_ID_MESSAGE:"1",
		MESSAGE_TYPE_ID_AUTHORIZATION:"2",
		MESSAGE_TYPE_ID_BOOKING:"3",

		
		JSON_RESPONSE_STATUS_OK: "ok",
		JSON_RESPONSE_STATUS_NOK: "nok",
		
		MESSAGE_STATE_PENDING	:"Pendiente",
		MESSAGE_STATE_AUTHORIZED:"Autorizado",
		MESSAGE_STATE_DENIED	:"No autorizado",

		LOGIN_ERROR_MESSAGE_GENERIC: "No puede ingresar. Por favor intentar mas tarde."
			
};